// Squirrelpedia Data
// Each species has a `type` (archetype) and `color` (palette key) that determine
// the inline SVG illustration. See svg-art.js for available archetypes.

const SQUIRRELS = {
  "North America": {
    icon: "🌲",
    note: "The continent's lawns, forests, and tundra host more sciurid diversity than any other — tree squirrels, ground squirrels, chipmunks, marmots, prairie dogs, and gliders.",
    species: [
      { name: "Eastern Gray Squirrel", sci: "Sciurus carolinensis", type: "tree", color: "gray",
        flavor: "The familiar park dweller — bold, acrobatic, and remarkably tolerant of human company.",
        life: "6–12 years (wild); up to 20 in captivity", climate: "Temperate deciduous & mixed forests",
        food: "Acorns, hickory nuts, seeds, fungi, occasional eggs", alive: "Tens of millions (very common)", friendly: 5 },
      { name: "Fox Squirrel", sci: "Sciurus niger", type: "tree", color: "rust",
        flavor: "North America's largest tree squirrel, with a luxuriant rust-orange coat.",
        life: "8–18 years", climate: "Open woodlands, oak-hickory forests",
        food: "Nuts, acorns, fruits, insects, bird eggs", alive: "Several million; widespread", friendly: 4 },
      { name: "American Red Squirrel", sci: "Tamiasciurus hudsonicus", type: "tree", color: "red",
        flavor: "Small, fierce, and famously territorial — the chattering scold of conifer forests.",
        life: "3–7 years (wild)", climate: "Boreal & montane coniferous forests",
        food: "Conifer seeds, mushrooms, buds, bark", alive: "Tens of millions", friendly: 2 },
      { name: "Douglas Squirrel", sci: "Tamiasciurus douglasii", type: "tree", color: "chestnut",
        flavor: "The 'pine squirrel' of the Pacific Northwest, described by John Muir as the 'most influential of all the Western forest animals.'",
        life: "5–8 years", climate: "Pacific coastal coniferous forests",
        food: "Douglas-fir cones, hemlock seeds, fungi", alive: "Common throughout range", friendly: 2 },
      { name: "Western Gray Squirrel", sci: "Sciurus griseus", type: "tree", color: "silver",
        flavor: "Shy and silver-coated, declining in parts of its range under pressure from eastern grays.",
        life: "7–11 years", climate: "Oak & pine woodlands of the West Coast",
        food: "Acorns, pine seeds, berries, fungi", alive: "Locally common; some populations threatened", friendly: 2 },
      { name: "Abert's Squirrel", sci: "Sciurus aberti", type: "tree", color: "gray-warm",
        flavor: "Unmistakable tufted ears and a near-exclusive bond with ponderosa pine forests.",
        life: "7–8 years", climate: "Ponderosa pine forests of the Southwest",
        food: "Ponderosa pine seeds, inner bark, fungi", alive: "Stable; ~hundreds of thousands", friendly: 2 },
      { name: "Arizona Gray Squirrel", sci: "Sciurus arizonensis", type: "tree", color: "gray",
        flavor: "A restricted-range specialist of riparian canyons in Arizona and New Mexico.",
        life: "5–7 years", climate: "Riparian woodlands in mountain canyons",
        food: "Walnuts, acorns, pine seeds, fruit", alive: "Limited range; status near-threatened", friendly: 2 },
      { name: "Southern Flying Squirrel", sci: "Glaucomys volans", type: "flying", color: "tawny",
        flavor: "Doesn't fly — glides on a patagium between wrist and ankle, often unseen by day-walking humans.",
        life: "5–6 years (wild); 10+ captive", climate: "Deciduous & mixed eastern forests",
        food: "Nuts, seeds, fungi, insects, bird eggs", alive: "Abundant but rarely seen (nocturnal)", friendly: 3 },
      { name: "Northern Flying Squirrel", sci: "Glaucomys sabrinus", type: "flying", color: "brown",
        flavor: "Boreal cousin of the southern glider; depends on truffle-like underground fungi.",
        life: "4–7 years", climate: "Boreal & montane conifer forests",
        food: "Lichens, fungi, seeds, nuts", alive: "Common across boreal North America", friendly: 3 },
      { name: "Humboldt's Flying Squirrel", sci: "Glaucomys oregonensis", type: "flying", color: "brown-dk",
        flavor: "Only described as a separate species in 2017 — the Pacific coast's secret glider.",
        life: "4–7 years", climate: "Pacific old-growth conifer forests",
        food: "Truffles, lichens, conifer seeds", alive: "Locally common; range-restricted", friendly: 3 },
      { name: "Eastern Chipmunk", sci: "Tamias striatus", type: "chipmunk", color: "rust",
        flavor: "Cheek pouches that stretch to triple head size; a one-animal seed-distribution service.",
        life: "2–3 years (wild); 8 captive", climate: "Deciduous forests & forest edges",
        food: "Seeds, nuts, berries, insects, fungi", alive: "Tens of millions", friendly: 4 },
      { name: "Least Chipmunk", sci: "Neotamias minimus", type: "chipmunk", color: "tawny",
        flavor: "The smallest and most widespread of the western chipmunks.",
        life: "2–6 years", climate: "Sagebrush, alpine tundra, boreal forest",
        food: "Seeds, nuts, berries, insects", alive: "Abundant across western N. America", friendly: 3 },
      { name: "Black-tailed Prairie Dog", sci: "Cynomys ludovicianus", type: "prairie-dog", color: "tawny",
        flavor: "Lives in vast 'towns' with complex linguistic alarm calls that encode predator type, size, and color.",
        life: "3–5 years (wild); 8+ captive", climate: "Shortgrass & mixed-grass prairie",
        food: "Grasses, forbs, seeds, occasional insects", alive: "Millions; <2% of historic numbers", friendly: 3 },
      { name: "Utah Prairie Dog", sci: "Cynomys parvidens", type: "prairie-dog", color: "cream",
        flavor: "Smallest prairie dog species, restricted to a sliver of southwestern Utah.",
        life: "3–5 years", climate: "High desert grasslands",
        food: "Grasses, flowers, seeds", alive: "~4,000 adults; federally threatened", friendly: 2 },
      { name: "Groundhog (Woodchuck)", sci: "Marmota monax", type: "marmot", color: "brown",
        flavor: "A solitary marmot famed for hibernation, weather prediction, and tunnel engineering.",
        life: "3–6 years (wild)", climate: "Meadows, woodland edges, farmlands",
        food: "Grasses, clover, alfalfa, fruits, bark", alive: "Millions; thriving in modified landscapes", friendly: 2 },
      { name: "Yellow-bellied Marmot", sci: "Marmota flaviventris", type: "marmot", color: "golden",
        flavor: "The 'whistle pig' of western talus slopes — sentinels of alpine meadows.",
        life: "13–15 years", climate: "Montane meadows, alpine rockfields",
        food: "Grasses, flowers, legumes, seeds", alive: "Abundant in mountain west", friendly: 2 },
      { name: "Hoary Marmot", sci: "Marmota caligata", type: "marmot", color: "silver",
        flavor: "The largest North American marmot, with silver-tipped fur and a piercing alarm whistle.",
        life: "Up to 15 years", climate: "Alpine talus & meadows",
        food: "Grasses, sedges, wildflowers, roots", alive: "Locally common in NW mountains", friendly: 2 },
      { name: "California Ground Squirrel", sci: "Otospermophilus beecheyi", type: "ground", color: "gray-warm",
        flavor: "Famous for chewing rattlesnake skin and rubbing it on themselves — a chemical disguise.",
        life: "3–4 years (wild); up to 10 captive", climate: "Grasslands, oak savannas, agricultural land",
        food: "Seeds, nuts, fruit, eggs, insects", alive: "Abundant; sometimes considered pest", friendly: 3 },
      { name: "Arctic Ground Squirrel", sci: "Urocitellus parryii", type: "ground", color: "tawny",
        flavor: "Hibernates with a body temperature below freezing — the only mammal known to do so.",
        life: "Up to 6 years", climate: "Arctic tundra",
        food: "Grasses, seeds, berries, lemmings, carrion", alive: "Common across the Arctic", friendly: 2 },
      { name: "Thirteen-lined Ground Squirrel", sci: "Ictidomys tridecemlineatus", type: "ground-striped", color: "tawny",
        flavor: "Striped like a chipmunk but ground-dwelling — a model organism for hibernation research.",
        life: "2–4 years (wild)", climate: "Short-grass prairies & mowed lawns",
        food: "Insects, seeds, grasses, mice, carrion", alive: "Abundant on Great Plains", friendly: 2 },
      { name: "Golden-mantled Ground Squirrel", sci: "Callospermophilus lateralis", type: "ground-striped", color: "golden",
        flavor: "Often mistaken for a chipmunk; lacks the head stripes that chipmunks bear.",
        life: "5–7 years", climate: "Montane forests & meadows",
        food: "Seeds, nuts, fruits, insects, eggs", alive: "Common in western mountains", friendly: 3 },
    ],
  },

  "South America": {
    icon: "🌴",
    note: "Squirrels here are concentrated in the genus Sciurus and its relatives — predominantly tropical tree squirrels of rainforest and cloud forest. No true ground squirrels, marmots, or prairie dogs occur natively.",
    species: [
      { name: "Guianan Squirrel", sci: "Guerlinguetus aestuans", type: "tree", color: "tawny",
        flavor: "Also called the Brazilian squirrel — a tawny canopy-dweller of Amazon and Atlantic forest.",
        life: "5–10 years", climate: "Lowland tropical rainforest",
        food: "Palm nuts, fruits, seeds, fungi", alive: "Widespread; population stable", friendly: 3 },
      { name: "Red-tailed Squirrel", sci: "Notosciurus granatensis", type: "tree", color: "rust",
        flavor: "Highly variable in coloration — over 30 described subspecies range from Costa Rica to Ecuador.",
        life: "6–8 years", climate: "Cloud forest & lowland rainforest",
        food: "Palm fruits, nuts, mushrooms, flowers", alive: "Common; least concern", friendly: 3 },
      { name: "Northern Amazon Red Squirrel", sci: "Sciurus igniventris", type: "tree", color: "flame",
        flavor: "Flame-bellied giant of the Amazon canopy — one of the larger Neotropical tree squirrels.",
        life: "6–10 years", climate: "Amazonian rainforest",
        food: "Brazil nuts, palm fruits, seeds", alive: "Common in undisturbed forest", friendly: 2 },
      { name: "Southern Amazon Red Squirrel", sci: "Sciurus spadiceus", type: "tree", color: "chestnut",
        flavor: "A heavyset Amazonian species, often heard before seen — a clattering call from the high canopy.",
        life: "6–10 years", climate: "Amazon basin lowland forests",
        food: "Palm nuts, hardwood seeds", alive: "Stable across range", friendly: 2 },
      { name: "Bolivian Squirrel", sci: "Sciurus ignitus", type: "tree", color: "rust",
        flavor: "Small montane squirrel of the eastern Andean foothills.",
        life: "5–8 years", climate: "Andean montane & cloud forest",
        food: "Seeds, fruits, fungi", alive: "Locally common", friendly: 2 },
      { name: "Junín Red Squirrel", sci: "Simosciurus pyrrhinus", type: "tree", color: "red-bright",
        flavor: "A rare endemic of central Peru's montane forest, known from few records.",
        life: "5–8 years (estimated)", climate: "Peruvian cloud forest",
        food: "Fruits, nuts, seeds", alive: "Data deficient; uncommon", friendly: 1 },
      { name: "Andean Squirrel", sci: "Hadrosciurus pucheranii", type: "tree", color: "brown-dk",
        flavor: "Small dark squirrel of the high Colombian Andes — among the highest-elevation Neotropical squirrels.",
        life: "4–7 years", climate: "Andean cloud forest, 2000–3500m",
        food: "Seeds, fruits, mosses", alive: "Restricted range; uncertain", friendly: 1 },
      { name: "Yellow-throated Squirrel", sci: "Hadrosciurus gilvigularis", type: "tree", color: "brown",
        flavor: "Distinctive yellow throat patch on an otherwise dark coat; Guiana Shield specialist.",
        life: "5–8 years", climate: "Lowland Guianan rainforest",
        food: "Nuts, palm fruits, seeds", alive: "Locally common", friendly: 2 },
    ],
  },

  "Europe": {
    icon: "🌳",
    note: "Europe hosts comparatively few sciurid species, but they loom large in folklore — from Ratatoskr, the gossiping squirrel of the Norse world tree, to Beatrix Potter's Squirrel Nutkin.",
    species: [
      { name: "Eurasian Red Squirrel", sci: "Sciurus vulgaris", type: "tree", color: "red-bright",
        flavor: "Tufted ears, russet coat — the native squirrel of Europe, in retreat before introduced grays in Britain and Italy.",
        life: "3–7 years (wild)", climate: "Coniferous & mixed temperate forests",
        food: "Pine seeds, hazelnuts, fungi, berries", alive: "~2.5 million in Europe; declining in west", friendly: 3 },
      { name: "Caucasian Squirrel", sci: "Sciurus anomalus", type: "tree", color: "brown",
        flavor: "Persian squirrel of the southern Caucasus and Anatolian forests.",
        life: "5–7 years", climate: "Broadleaf forests of the Caucasus & Levant",
        food: "Hazelnuts, acorns, beech mast, fruit", alive: "Stable; least concern", friendly: 3 },
      { name: "Alpine Marmot", sci: "Marmota marmota", type: "marmot", color: "tawny",
        flavor: "Sentinels of the high Alps, hibernating six months in family burrow systems.",
        life: "15–18 years", climate: "Alpine meadows above 800m",
        food: "Grasses, herbs, flowers, roots", alive: "~100,000+ across European mountains", friendly: 3 },
      { name: "European Ground Squirrel (Souslik)", sci: "Spermophilus citellus", type: "ground", color: "cream",
        flavor: "Once common across pastoral Europe, now endangered as steppe habitats are plowed.",
        life: "2–5 years", climate: "Dry grassland & steppe",
        food: "Seeds, grasses, insects, roots", alive: "Endangered; fragmented populations", friendly: 2 },
      { name: "Speckled Ground Squirrel", sci: "Spermophilus suslicus", type: "ground", color: "gray-warm",
        flavor: "Mottled coat camouflages it on the Pontic-Caspian steppe.",
        life: "3–5 years", climate: "Eastern European steppe",
        food: "Grasses, seeds, bulbs", alive: "Vulnerable; declining", friendly: 2 },
    ],
  },

  "Asia": {
    icon: "🎋",
    note: "Home to the greatest sciurid diversity on Earth — giant tree squirrels weighing nearly 3 kg, miniature striped palm squirrels, and a host of flying squirrels that glide between the buttressed trees of tropical forests.",
    species: [
      { name: "Indian Giant Squirrel", sci: "Ratufa indica", type: "giant", color: "multicolor",
        flavor: "Up to a meter long including tail, multicolored in maroon, purple, and cream — a treetop spectacle of the Western Ghats.",
        life: "15–20 years", climate: "Tropical deciduous & evergreen forest",
        food: "Fruits, flowers, nuts, bark, insects", alive: "Tens of thousands; range-restricted", friendly: 1 },
      { name: "Black Giant Squirrel", sci: "Ratufa bicolor", type: "giant", color: "black",
        flavor: "A jet-black canopy giant of Southeast Asia, sometimes traveling 6 meters in a single leap.",
        life: "15–20 years", climate: "Tropical & subtropical forest",
        food: "Fruits, seeds, leaves, insects", alive: "Near threatened; declining", friendly: 1 },
      { name: "Cream-coloured Giant Squirrel", sci: "Ratufa affinis", type: "giant", color: "cream",
        flavor: "Sundaic relative of the giants, pale-bodied, gliding through the dipterocarp canopy.",
        life: "15–20 years", climate: "Sundaic lowland rainforest",
        food: "Fruits, seeds, leaves", alive: "Near threatened; logging-impacted", friendly: 1 },
      { name: "Grizzled Giant Squirrel", sci: "Ratufa macroura", type: "giant", color: "silver",
        flavor: "Restricted to a few riverine forests of southern India and Sri Lanka.",
        life: "15–20 years", climate: "Riparian forest, dry deciduous",
        food: "Fruits, flowers, bark, eggs", alive: "<1,000 in India; near threatened", friendly: 1 },
      { name: "Pallas's Squirrel", sci: "Callosciurus erythraeus", type: "tree", color: "chestnut",
        flavor: "Highly adaptive; introduced populations have established in Europe, Japan, and Argentina.",
        life: "6–10 years", climate: "Tropical & subtropical forest",
        food: "Fruits, seeds, bark, insects", alive: "Abundant; invasive in places", friendly: 3 },
      { name: "Finlayson's Squirrel", sci: "Callosciurus finlaysonii", type: "tree", color: "cream",
        flavor: "Sixteen described subspecies in colors from cream-white to chocolate to black.",
        life: "5–10 years", climate: "Tropical forests & city parks of SE Asia",
        food: "Fruits, seeds, flowers", alive: "Common; thrives in cities", friendly: 4 },
      { name: "Indian Palm Squirrel", sci: "Funambulus palmarum", type: "palm", color: "tawny",
        flavor: "Three pale stripes said in Hindu legend to be left by Lord Rama's fingers in gratitude.",
        life: "5–7 years", climate: "Tropical urban gardens & forests",
        food: "Fruits, nuts, seeds, flowers, eggs", alive: "Tens of millions", friendly: 5 },
      { name: "Northern Palm Squirrel", sci: "Funambulus pennantii", type: "palm", color: "gray-warm",
        flavor: "Five-striped cousin of the palm squirrel; ubiquitous in northern Indian cities.",
        life: "5–7 years", climate: "Urban, agricultural, scrub forest",
        food: "Fruits, seeds, grains, eggs", alive: "Abundant; urban adapter", friendly: 5 },
      { name: "Japanese Squirrel", sci: "Sciurus lis", type: "tree", color: "brown",
        flavor: "An endemic of Honshu, Shikoku, and Kyushu — extirpated from Kyushu in recent times.",
        life: "5–7 years", climate: "Mixed broadleaf & conifer forest",
        food: "Walnuts, pine seeds, mushrooms", alive: "Locally common; some declines", friendly: 2 },
      { name: "Siberian Flying Squirrel", sci: "Pteromys volans", type: "flying", color: "silver",
        flavor: "Saucer-eyed nocturnal glider of the Eurasian taiga; protected and beloved in Finland.",
        life: "3–5 years (wild)", climate: "Boreal & temperate forest",
        food: "Buds, leaves, catkins, seeds", alive: "Vulnerable in EU; common in Siberia", friendly: 2 },
      { name: "Red Giant Flying Squirrel", sci: "Petaurista petaurista", type: "flying", color: "rust",
        flavor: "Capable of glides exceeding 75 meters — a flame-colored shape across the moonlit canopy.",
        life: "10–16 years", climate: "Tropical & subtropical forest",
        food: "Leaves, fruits, nuts, bark", alive: "Widespread; locally common", friendly: 1 },
      { name: "Himalayan Striped Squirrel", sci: "Tamiops mcclellandii", type: "palm", color: "olive",
        flavor: "Tiny, hyperactive, and chipmunk-striped — flits through Himalayan and Indochinese forests.",
        life: "4–6 years", climate: "Subtropical & montane broadleaf forest",
        food: "Fruits, nectar, insects, seeds", alive: "Abundant", friendly: 3 },
      { name: "Long-tailed Marmot", sci: "Marmota caudata", type: "marmot", color: "golden",
        flavor: "Golden marmot of the high Pamir, Tien Shan, and Karakoram — among the highest-living mammals.",
        life: "10–15 years", climate: "Alpine meadows 2400–3800m",
        food: "Alpine grasses, sedges, flowers", alive: "Stable; data limited", friendly: 2 },
      { name: "Himalayan Marmot", sci: "Marmota himalayana", type: "marmot", color: "brown",
        flavor: "The marmot of Tibetan plateau pastures, sometimes habituated by trekkers and nomads.",
        life: "13–15 years", climate: "Tibetan plateau, alpine meadows",
        food: "Grasses, herbs, flowers", alive: "Locally abundant", friendly: 2 },
      { name: "Red-cheeked Ground Squirrel", sci: "Spermophilus erythrogenys", type: "ground", color: "rust",
        flavor: "Kazakh steppe specialist with chestnut markings on its face.",
        life: "3–4 years", climate: "Central Asian steppe & semi-desert",
        food: "Grasses, seeds, bulbs, insects", alive: "Locally common", friendly: 2 },
    ],
  },

  "Africa": {
    icon: "🌾",
    note: "African sciurids fall into two main lineages: the tree squirrels of forest and woodland, and the ground squirrels of arid plains. Notably, Africa hosts the world's smallest squirrel, weighing barely 10 grams.",
    species: [
      { name: "African Pygmy Squirrel", sci: "Myosciurus pumilio", type: "pygmy", color: "brown",
        flavor: "The smallest squirrel in the world — head and body barely 7 centimeters, weighing about as much as a chestnut.",
        life: "4–5 years (estimated)", climate: "Lowland Central African rainforest",
        food: "Bark scrapings, lichens, ants, fruit", alive: "Locally common but rarely seen", friendly: 1 },
      { name: "Cape Ground Squirrel", sci: "Geosciurus inauris", type: "ground-striped", color: "cream",
        flavor: "Uses its bushy tail as a parasol against the Kalahari sun — a literal sun-shade.",
        life: "11–12 years", climate: "Arid southern African savanna",
        food: "Bulbs, seeds, grasses, insects", alive: "Abundant", friendly: 3 },
      { name: "Striped Ground Squirrel", sci: "Euxerus erythropus", type: "ground-striped", color: "tawny",
        flavor: "A single white flank stripe distinguishes this Sahelian and West African digger.",
        life: "6–9 years", climate: "Savanna, dry woodland, scrub",
        food: "Seeds, roots, insects, small vertebrates", alive: "Widespread; least concern", friendly: 2 },
      { name: "Smith's Bush Squirrel", sci: "Paraxerus cepapi", type: "tree", color: "olive",
        flavor: "The 'tree squirrel of the bushveld' — common in Kruger and surrounding savannas.",
        life: "8–10 years", climate: "Miombo and acacia woodlands",
        food: "Seeds, fruits, flowers, insects", alive: "Abundant", friendly: 3 },
      { name: "Red-legged Sun Squirrel", sci: "Heliosciurus rufobrachium", type: "tree", color: "rust",
        flavor: "Often sunning itself on exposed branches — hence 'sun squirrel.'",
        life: "6–9 years", climate: "West and Central African forests",
        food: "Fruits, nuts, bark, insects", alive: "Common", friendly: 2 },
      { name: "Gambian Sun Squirrel", sci: "Heliosciurus gambianus", type: "tree", color: "cream",
        flavor: "Pale-faced relative across drier West African woodland.",
        life: "6–9 years", climate: "Savanna woodland, gallery forest",
        food: "Fruits, palm nuts, insects", alive: "Locally common", friendly: 2 },
      { name: "Geoffroy's Ground Squirrel", sci: "Xerus rutilus", type: "ground", color: "tawny",
        flavor: "The unstriped ground squirrel of the Horn of Africa — a familiar sight in Kenyan and Ethiopian dry country.",
        life: "5–7 years", climate: "Semi-arid bushland & savanna",
        food: "Seeds, bulbs, insects, eggs", alive: "Common in suitable habitat", friendly: 3 },
      { name: "Mountain Ground Squirrel", sci: "Geosciurus princeps", type: "ground", color: "gray-warm",
        flavor: "A Namibian endemic of rocky escarpments, less common than its Cape cousin.",
        life: "8–10 years", climate: "Arid mountains & escarpments",
        food: "Seeds, bulbs, leaves", alive: "Restricted range; uncommon", friendly: 2 },
    ],
  },

  "Australia & Oceania": {
    icon: "🦘",
    note: "No squirrels are native to Australia, New Zealand, or the broader Oceanian region — the visual analogs (sugar gliders, possums) are marsupials in an entirely separate mammalian lineage. A few introduced populations have been recorded.",
    species: [
      { name: "Northern Palm Squirrel (introduced)", sci: "Funambulus pennantii", type: "palm", color: "gray-warm",
        flavor: "Released near Perth, Western Australia around 1898. A small flourishing population persists — the only established squirrel in Australia.",
        life: "5–7 years", climate: "Suburban gardens, parks (introduced)",
        food: "Fruits, seeds, flowers, eggs", alive: "Localized population around Perth", friendly: 4 },
      { name: "Eastern Gray Squirrel (extirpated)", sci: "Sciurus carolinensis", type: "tree", color: "gray",
        flavor: "Introduced to Ballarat, Victoria in 1937. Apparently extinct in Australia by the late 20th century — gone but historically noted.",
        life: "6–12 years", climate: "Was: temperate woodland (introduced)",
        food: "Acorns, nuts, seeds, eggs", alive: "Extirpated from Australia", friendly: 5 },
    ],
  },

  "Antarctica": {
    icon: "❄️",
    note: "No squirrels — extant or fossil — are known from Antarctica. The continent's terrestrial mammal fauna is, and has long been, essentially absent. (Listed here for completeness; even a field guide must admit where the family does not tread.)",
    species: [],
  },

  "Prehistoric & Extinct": {
    icon: "🦴",
    note: "Squirrels are an ancient lineage stretching back roughly 36 million years to the late Eocene. The earliest forms were tree-dwelling, and the family has since diversified, contracted, and dispersed many times over. Illustrations show fossil silhouettes; living color is, of course, lost to time.",
    species: [
      { name: "Douglassciurus", sci: "Douglassciurus jeffersoni", type: "prehistoric", color: "fossil",
        flavor: "The oldest known squirrel, from late Eocene Wyoming — already strikingly modern in skeleton.",
        life: "Unknown", climate: "Late Eocene subtropical woodland (~36 Ma)",
        food: "Likely seeds & nuts; arboreal", alive: "Extinct (no living individuals)", friendly: 0, extinct: true },
      { name: "Hesperopetes", sci: "Hesperopetes thoringtoni", type: "prehistoric", color: "fossil",
        flavor: "An Eocene North American sciurid known from teeth and jaw fragments; a contemporary of the earliest squirrels.",
        life: "Unknown", climate: "Late Eocene–Oligocene forests",
        food: "Seeds and plant matter (inferred)", alive: "Extinct", friendly: 0, extinct: true },
      { name: "Palaeosciurus", sci: "Palaeosciurus spp.", type: "prehistoric", color: "fossil",
        flavor: "Oligocene–Miocene European squirrels; some species were arboreal, others apparently terrestrial.",
        life: "Unknown", climate: "Oligocene–Miocene Europe",
        food: "Seeds, nuts, fungi", alive: "Extinct", friendly: 0, extinct: true },
      { name: "Protosciurus", sci: "Protosciurus spp.", type: "prehistoric", color: "fossil",
        flavor: "Tree squirrels of the Oligocene of North America; among the earliest members of the modern tree-squirrel radiation.",
        life: "Unknown", climate: "Oligocene forests of N. America (~30 Ma)",
        food: "Arboreal, seed-eating", alive: "Extinct", friendly: 0, extinct: true },
      { name: "Cedromus", sci: "Cedromus wilsoni", type: "prehistoric", color: "fossil",
        flavor: "A small Oligocene squirrel of North America, sometimes considered close to the ancestry of flying squirrels.",
        life: "Unknown", climate: "Oligocene N. America",
        food: "Likely seeds and arboreal browse", alive: "Extinct", friendly: 0, extinct: true },
      { name: "Miopetaurista", sci: "Miopetaurista spp.", type: "prehistoric", color: "fossil",
        flavor: "A genus of giant flying squirrels from the Miocene of Eurasia and North America — some species rivaled today's largest gliders.",
        life: "Unknown", climate: "Miocene temperate forests",
        food: "Leaves, fruits (inferred)", alive: "Extinct", friendly: 0, extinct: true },
      { name: "Sciurion", sci: "Sciurion campestre", type: "prehistoric", color: "fossil",
        flavor: "Miocene squirrel of North American grasslands — among the early ground-adapted sciurids.",
        life: "Unknown", climate: "Miocene grasslands",
        food: "Seeds, grasses", alive: "Extinct", friendly: 0, extinct: true },
      { name: "Spermophilinus", sci: "Spermophilinus bredai", type: "prehistoric", color: "fossil",
        flavor: "European Miocene ground squirrel, often abundant in fossil rodent faunas of the period.",
        life: "Unknown", climate: "Miocene woodlands of Europe",
        food: "Seeds, plant material", alive: "Extinct", friendly: 0, extinct: true },
      { name: "Plesiosciurus", sci: "Plesiosciurus sansaniensis", type: "prehistoric", color: "fossil",
        flavor: "A Miocene European tree squirrel known mainly from the famous Sansan locality in France.",
        life: "Unknown", climate: "Miocene Europe",
        food: "Nuts, seeds (inferred)", alive: "Extinct", friendly: 0, extinct: true },
      { name: "Heteroxerus", sci: "Heteroxerus spp.", type: "prehistoric", color: "fossil",
        flavor: "Extinct ground squirrels of Miocene Europe, related to the modern African Xerus lineage.",
        life: "Unknown", climate: "Miocene European open habitats",
        food: "Seeds, roots, grasses", alive: "Extinct", friendly: 0, extinct: true },
      { name: "Marmota minor", sci: "Marmota minor", type: "prehistoric", color: "fossil",
        flavor: "An extinct marmot from the late Miocene of North America — among the earliest members of the genus.",
        life: "Unknown", climate: "Late Miocene grasslands",
        food: "Grasses, forbs", alive: "Extinct", friendly: 0, extinct: true },
      { name: "Tamias aristus", sci: "Tamias aristus", type: "prehistoric", color: "fossil",
        flavor: "A Pleistocene chipmunk from the southeastern United States — larger than any living chipmunk.",
        life: "Unknown", climate: "Pleistocene SE North America",
        food: "Seeds, nuts (inferred)", alive: "Extinct", friendly: 0, extinct: true },
      { name: "Oligospermophilus", sci: "Oligospermophilus spp.", type: "prehistoric", color: "fossil",
        flavor: "An Oligocene–Miocene sciurid lineage of Eurasia, representing an early stage in ground-squirrel evolution.",
        life: "Unknown", climate: "Oligo-Miocene Eurasia",
        food: "Plant material", alive: "Extinct", friendly: 0, extinct: true },
      { name: "Hylopetes praesonus", sci: "Hylopetes praesonus", type: "prehistoric", color: "fossil",
        flavor: "A Miocene flying squirrel of Asia, ancestor or close relative to the modern arrow-tailed flying squirrels.",
        life: "Unknown", climate: "Miocene Asian forests",
        food: "Leaves, seeds, bark", alive: "Extinct", friendly: 0, extinct: true },
    ],
  },
};

const FRIENDLINESS_LABELS = {
  0: "Not applicable",
  1: "Wary — avoids humans",
  2: "Skittish — keeps a distance",
  3: "Curious — can be approached",
  4: "Bold — often takes food",
  5: "Habituated — practically a roommate",
};
